name = "cvlift-tools-api"
main = "src/index.js"
compatibility_date = "2026-03-26"

[[kv_namespaces]]
binding = "RATE_LIMITS"
id = "54645e77a7da457394641be375bcac99"

[vars]
ENVIRONMENT = "production"

[[routes]]
pattern = "api.cvlift.me/tool"
zone_name = "cvlift.me"